/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main.view;

import Main.controller.MessageController;
import java.awt.Color;
import javax.swing.*;
import Main.controller.FriendController;
import Main.controller.GroupController;
import Main.entity.Friend;
import Main.entity.Group;
import Main.entity.MessageEntity;
import Main.file.File;
import java.util.ArrayList;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.socket.SocketThread;
import Main.shareEnv.*;


/**
 *
 * @author HP-PC
 */
public class chatboxGroup extends javax.swing.JFrame {
    static ArrayList<Group> groups = new ArrayList<>();    
    ArrayList<MessageEntity> historyMessage = new ArrayList<>();
    
    
    static {
        SocketThread.startSocket(Share.socketHost, Share.socketPort);
    }
            
            
    /**
     * Creates new form boxChat
     */
    public chatboxGroup() {
        String userId = File.readFromFile();
        SocketThread.sendIdUser(userId);
        groups = GroupController.apiGroupList();
        initComponents();
        initUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        home = new javax.swing.JPanel();
        friendChat = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        group1 = new javax.swing.JPanel();
        avatar1 = new javax.swing.JLabel();
        message1 = new javax.swing.JLabel();
        groupname1 = new javax.swing.JLabel();
        group2 = new javax.swing.JPanel();
        avatar2 = new javax.swing.JLabel();
        message2 = new javax.swing.JLabel();
        groupname2 = new javax.swing.JLabel();
        group3 = new javax.swing.JPanel();
        avatar3 = new javax.swing.JLabel();
        message3 = new javax.swing.JLabel();
        groupname3 = new javax.swing.JLabel();
        group4 = new javax.swing.JPanel();
        avatar4 = new javax.swing.JLabel();
        message4 = new javax.swing.JLabel();
        groupname4 = new javax.swing.JLabel();
        group5 = new javax.swing.JPanel();
        avatar5 = new javax.swing.JLabel();
        message5 = new javax.swing.JLabel();
        groupname5 = new javax.swing.JLabel();
        group6 = new javax.swing.JPanel();
        avatar6 = new javax.swing.JLabel();
        message6 = new javax.swing.JLabel();
        groupname6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        chatPerson = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        more = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        sendMessage = new javax.swing.JTextField();
        send = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        homebtn = new javax.swing.JPanel();
        chatLabel3 = new javax.swing.JLabel();
        chatbtn = new javax.swing.JPanel();
        chatLabel7 = new javax.swing.JLabel();
        groupbtn = new javax.swing.JPanel();
        chatLabel8 = new javax.swing.JLabel();
        favouritebtn = new javax.swing.JPanel();
        chatLabel9 = new javax.swing.JLabel();
        otherbtn = new javax.swing.JPanel();
        chatLabel10 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JPanel();
        chatLabel11 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Screen");

        home.setBackground(new java.awt.Color(255, 255, 255));

        friendChat.setBackground(new java.awt.Color(128, 161, 183));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("Search here");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/Main.icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );

        group1.setBackground(new java.awt.Color(128, 206, 202));
        group1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                group1Click(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                group1Press(evt);
            }
        });

        avatar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N

        message1.setText("New message");

        groupname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        groupname1.setForeground(new java.awt.Color(255, 255, 255));
        groupname1.setText("Nhom");

        javax.swing.GroupLayout group1Layout = new javax.swing.GroupLayout(group1);
        group1.setLayout(group1Layout);
        group1Layout.setHorizontalGroup(
            group1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(group1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupname1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        group1Layout.setVerticalGroup(
            group1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(group1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(group1Layout.createSequentialGroup()
                        .addComponent(groupname1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        group2.setBackground(new java.awt.Color(128, 161, 183));
        group2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                group2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                group2Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                group2Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                group2Press(evt);
            }
        });

        avatar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N

        message2.setText("New message");

        groupname2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        groupname2.setForeground(new java.awt.Color(255, 255, 255));
        groupname2.setText("Phan Thanh An");

        javax.swing.GroupLayout group2Layout = new javax.swing.GroupLayout(group2);
        group2.setLayout(group2Layout);
        group2Layout.setHorizontalGroup(
            group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupname2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        group2Layout.setVerticalGroup(
            group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(group2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(group2Layout.createSequentialGroup()
                        .addComponent(groupname2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        group3.setBackground(new java.awt.Color(128, 161, 183));
        group3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                group3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                group3Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                group3Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                group3Press(evt);
            }
        });

        avatar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N

        message3.setText("New message");

        groupname3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        groupname3.setForeground(new java.awt.Color(255, 255, 255));
        groupname3.setText("Le Nguyen Thai");

        javax.swing.GroupLayout group3Layout = new javax.swing.GroupLayout(group3);
        group3.setLayout(group3Layout);
        group3Layout.setHorizontalGroup(
            group3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(group3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupname3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        group3Layout.setVerticalGroup(
            group3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(group3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(group3Layout.createSequentialGroup()
                        .addComponent(groupname3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        group4.setBackground(new java.awt.Color(128, 161, 183));
        group4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                group4Click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                group4Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                group4Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                group4Press(evt);
            }
        });

        avatar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N

        message4.setText("New message");

        groupname4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        groupname4.setForeground(new java.awt.Color(255, 255, 255));
        groupname4.setText("Nguyen Nhat Nam");

        javax.swing.GroupLayout group4Layout = new javax.swing.GroupLayout(group4);
        group4.setLayout(group4Layout);
        group4Layout.setHorizontalGroup(
            group4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(group4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupname4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        group4Layout.setVerticalGroup(
            group4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(group4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(group4Layout.createSequentialGroup()
                        .addComponent(groupname4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        group5.setBackground(new java.awt.Color(128, 161, 183));
        group5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                group5Click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                group5Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                group5Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                group5Press(evt);
            }
        });

        avatar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N

        message5.setText("New message");

        groupname5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        groupname5.setForeground(new java.awt.Color(255, 255, 255));
        groupname5.setText("Nguyen Nhat Nam");

        javax.swing.GroupLayout group5Layout = new javax.swing.GroupLayout(group5);
        group5.setLayout(group5Layout);
        group5Layout.setHorizontalGroup(
            group5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(group5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupname5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        group5Layout.setVerticalGroup(
            group5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(group5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(group5Layout.createSequentialGroup()
                        .addComponent(groupname5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        group6.setBackground(new java.awt.Color(128, 161, 183));
        group6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                group6Click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                group6Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                group6Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                group6Press(evt);
            }
        });

        avatar6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N

        message6.setText("New message");

        groupname6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        groupname6.setForeground(new java.awt.Color(255, 255, 255));
        groupname6.setText("Nguyen Nhat Nam");

        javax.swing.GroupLayout group6Layout = new javax.swing.GroupLayout(group6);
        group6.setLayout(group6Layout);
        group6Layout.setHorizontalGroup(
            group6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(group6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupname6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        group6Layout.setVerticalGroup(
            group6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(group6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(group6Layout.createSequentialGroup()
                        .addComponent(groupname6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout friendChatLayout = new javax.swing.GroupLayout(friendChat);
        friendChat.setLayout(friendChatLayout);
        friendChatLayout.setHorizontalGroup(
            friendChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(group1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(group2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(group3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(group4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(group5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(group6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        friendChatLayout.setVerticalGroup(
            friendChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendChatLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(128, 161, 183));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-user-30 (1).png"))); // NOI18N

        chatPerson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatPerson.setForeground(new java.awt.Color(255, 255, 255));
        chatPerson.setText("Bao Pham Hong Gia");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-spam-30.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-denied-30 (1).png"))); // NOI18N

        more.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        more.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-menu-30.png"))); // NOI18N
        more.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moreMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(more)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(more, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(128, 190, 183));

        sendMessage.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageActionPerformed(evt);
            }
        });

        send.setBackground(new java.awt.Color(128, 190, 183));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-send-30 (1).png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendMouseExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sendMessageToServer(evt);
            }
        });

        javax.swing.GroupLayout sendLayout = new javax.swing.GroupLayout(send);
        send.setLayout(sendLayout);
        sendLayout.setHorizontalGroup(
            sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        sendLayout.setVerticalGroup(
            sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendMessage)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        area.setColumns(20);
        area.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(friendChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(friendChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(128, 190, 183));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-paper-plane-message-100.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ZALU");

        homebtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel3.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel3.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-home-30.png"))); // NOI18N
        chatLabel3.setText("Home");
        chatLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout homebtnLayout = new javax.swing.GroupLayout(homebtn);
        homebtn.setLayout(homebtnLayout);
        homebtnLayout.setHorizontalGroup(
            homebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homebtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homebtnLayout.setVerticalGroup(
            homebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        chatbtn.setBackground(new java.awt.Color(128, 190, 183));
        chatbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chatEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chatExit(evt);
            }
        });

        chatLabel7.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel7.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-chat-30.png"))); // NOI18N
        chatLabel7.setText("Chat Box");
        chatLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chatLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout chatbtnLayout = new javax.swing.GroupLayout(chatbtn);
        chatbtn.setLayout(chatbtnLayout);
        chatbtnLayout.setHorizontalGroup(
            chatbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chatbtnLayout.setVerticalGroup(
            chatbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        groupbtn.setBackground(new java.awt.Color(128, 161, 183));

        chatLabel8.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel8.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N
        chatLabel8.setText("Group Chat");
        chatLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                groupExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                groupScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout groupbtnLayout = new javax.swing.GroupLayout(groupbtn);
        groupbtn.setLayout(groupbtnLayout);
        groupbtnLayout.setHorizontalGroup(
            groupbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        );
        groupbtnLayout.setVerticalGroup(
            groupbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        favouritebtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel9.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel9.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-star-30.png"))); // NOI18N
        chatLabel9.setText("Friend");
        chatLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favouriteEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favoutiteExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                favouriteScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout favouritebtnLayout = new javax.swing.GroupLayout(favouritebtn);
        favouritebtn.setLayout(favouritebtnLayout);
        favouritebtnLayout.setHorizontalGroup(
            favouritebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favouritebtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        favouritebtnLayout.setVerticalGroup(
            favouritebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        otherbtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel10.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel10.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-setting-30.png"))); // NOI18N
        chatLabel10.setText("Others");
        chatLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                otherEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                otherExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                otherScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout otherbtnLayout = new javax.swing.GroupLayout(otherbtn);
        otherbtn.setLayout(otherbtnLayout);
        otherbtnLayout.setHorizontalGroup(
            otherbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otherbtnLayout.setVerticalGroup(
            otherbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        logoutbtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel11.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel11.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-logout-30.png"))); // NOI18N
        chatLabel11.setText("Log out");
        chatLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout logoutbtnLayout = new javax.swing.GroupLayout(logoutbtn);
        logoutbtn.setLayout(logoutbtnLayout);
        logoutbtnLayout.setHorizontalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutbtnLayout.setVerticalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chatbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(groupbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(favouritebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(otherbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(groupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(favouritebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(otherbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeScreenMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new homeScreen().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_homeScreenMousePressed

    private void chatLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel7MouseClicked

    private void chatLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel7MousePressed

    private void chatLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel8MouseClicked

    private void groupScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupScreenMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override 
           public void run() {
               new groupchat().setVisible(true);
           }
        });
    }//GEN-LAST:event_groupScreenMousePressed

    private void chatLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel9MouseClicked

    private void favouriteScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouriteScreenMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override 
           public void run() {
               new friendScreen().setVisible(true);
           }
        });
    }//GEN-LAST:event_favouriteScreenMousePressed

    private void chatLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel10MouseClicked

    private void otherScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherScreenMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run(){
                new otherScreen().setVisible(true);
            }
        });
    }//GEN-LAST:event_otherScreenMousePressed

    private void chatLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel11MouseClicked

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run(){
                new loginForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_logoutMousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMessageActionPerformed

    private void sendMouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseEnter
        // TODO add your handling code here:
        //setColor(send);
    }//GEN-LAST:event_sendMouseEnter

    private void sendMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseExit
        resetColor(send);    }//GEN-LAST:event_sendMouseExit

    private void homeEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeEnter
        // TODO add your handling code here:
        //setColor(homebtn);
    }//GEN-LAST:event_homeEnter

    private void homeExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeExit
        // TODO add your handling code here:
        //resetColor(homebtn);
    }//GEN-LAST:event_homeExit

    private void groupExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupExit
        // TODO add your handling code here:
        //resetColor(groupbtn);
    }//GEN-LAST:event_groupExit

    private void favouriteEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouriteEnter
        // TODO add your handling code here:
        //setColor(favouritebtn);
    }//GEN-LAST:event_favouriteEnter

    private void favoutiteExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoutiteExit
        // TODO add your handling code here:
        //resetColor(favouritebtn);
    }//GEN-LAST:event_favoutiteExit

    private void otherEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherEnter
        // TODO add your handling code here:
        //setColor(otherbtn);

    }//GEN-LAST:event_otherEnter

    private void otherExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherExit
        // TODO add your handling code here:
        //resetColor(otherbtn);
    }//GEN-LAST:event_otherExit

    private void logoutEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutEnter
        // TODO add your handling code here:
        setColor(logoutbtn);
    }//GEN-LAST:event_logoutEnter

    private void logoutExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutExit
        // TODO add your handling code here:
        //resetColor(logoutbtn);
    }//GEN-LAST:event_logoutExit

    private void chatEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatEnter
        // TODO add your handling code here:
        //setColor(chatbtn);
    }//GEN-LAST:event_chatEnter

    private void chatExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatExit
        // TODO add your handling code here:
        //resetColor(chatbtn);
    }//GEN-LAST:event_chatExit

    private void group2Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group2Enter
        // TODO add your handling code here:
        //setColor1(user2);
    }//GEN-LAST:event_group2Enter

    private void group2Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group2Exit
        // TODO add your handling code here:
        //setColor(user2);
    }//GEN-LAST:event_group2Exit

    private void group3Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group3Enter
        // TODO add your handling code here:
        //setColor1(user3);
    }//GEN-LAST:event_group3Enter

    private void group3Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group3Exit
        // TODO add your handling code here:
        //setColor(user3);
    }//GEN-LAST:event_group3Exit

    private void group4Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group4Enter
        // TODO add your handling code here:
       // setColor1(user4);
    }//GEN-LAST:event_group4Enter

    private void group4Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group4Exit
        // TODO add your handling code here:
        //setColor(user4);
    }//GEN-LAST:event_group4Exit

    private void group4Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group4Click
        // TODO add your handling code here:
        //setColor1(user4);
    }//GEN-LAST:event_group4Click

    private void group1Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group1Click
        // TODO add your handling code here:
        //setColor1(user1);
    }//GEN-LAST:event_group1Click

    private void group2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group2MouseClicked
        // TODO add your handling code here:
        //setColor1(user2);
    }//GEN-LAST:event_group2MouseClicked

    private void group3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group3MouseClicked
        // TODO add your handling code here:
       // setColor1(user3);
    }//GEN-LAST:event_group3MouseClicked

    private void group2Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group2Press
        // TODO add your handling code here:
        chatPerson.setText(groups.get(1).getUsername());
        setColor1(group2);
        setColor(group1);        
        setColor(group3);
        setColor(group4);
        setColor(group5);
        setColor(group6);
        
        String username2 = groups.get(1).getUsername();
        ArrayList<MessageEntity> historyUser = MessageController.getHistoryMessage(username2);


        area.setText("");
        for (MessageEntity i : historyUser){
            if (i.getsenderId().endsWith(File.readFromFile())) {
                String appendtxt = "@YOU: " + i.getMessage() + "\n";
                area.append(appendtxt);
            } else {
                String appendtxt = "@" + username2 + ": " + i.getMessage() + "\n";
                area.append(appendtxt);
            }
        }

    }//GEN-LAST:event_group2Press

    private void group1Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group1Press
        // TODO add your handling code here:
        
        setColor1(group1);
        chatPerson.setText(groups.get(0).getUsername());
        setColor(group2);        
        setColor(group3);
        setColor(group4);        
        setColor(group5);
        setColor(group6);
        
        String username = groups.get(0).getUsername();
        ArrayList<MessageEntity> historyUser = MessageController.getHistoryMessage(groups.get(0).getUsername());
        area.setText("");
        for (MessageEntity i : historyUser){
            if (i.getsenderId().endsWith(File.readFromFile())) {
                String appendtxt = "@YOU: " + i.getMessage() + "\n";
                area.append(appendtxt);
            } else {
                String appendtxt = "@" + username + ": " + i.getMessage() + "\n";
                area.append(appendtxt);
            }
        }

    }//GEN-LAST:event_group1Press

    private void group3Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group3Press
        // TODO add your handling code here:
        setColor1(group3);
        chatPerson.setText(groups.get(2).getUsername());
        setColor(group2);        
        setColor(group1);
        setColor(group4);
        setColor(group5);
        setColor(group6);
        
        String username = groups.get(2).getUsername();
        ArrayList<MessageEntity> historyUser = MessageController.getHistoryMessage(groups.get(2).getUsername());
        area.setText("");
        for (MessageEntity i : historyUser){
            if (i.getsenderId().endsWith(File.readFromFile())) {
                String appendtxt = "@YOU: " + i.getMessage() + "\n";
                area.append(appendtxt);
            } else {
                String appendtxt = "@" + username + ": " + i.getMessage() + "\n";
                area.append(appendtxt);
            }
        }
    }//GEN-LAST:event_group3Press

    private void group4Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group4Press
        // TODO add your handling code here:
        setColor1(group4);
        chatPerson.setText(groups.get(3).getUsername());
        setColor(group2);        
        setColor(group1);
        setColor(group3);
        setColor(group5);
        setColor(group6);       
        
                
        String username = groups.get(3).getUsername();
        ArrayList<MessageEntity> historyUser = MessageController.getHistoryMessage(groups.get(3).getUsername());
        area.setText("");
        for (MessageEntity i : historyUser){
            if (i.getsenderId().endsWith(File.readFromFile())) {
                String appendtxt = "@YOU: " + i.getMessage() + "\n";
                area.append(appendtxt);
            } else {
                String appendtxt = "@" + username + ": " + i.getMessage() + "\n";
                area.append(appendtxt);
            }
        }
    }//GEN-LAST:event_group4Press

    private void sendMessageToServer(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageToServer
        // TODO add your handling code here:
        String getMess = sendMessage.getText();
        String sender = "You";
        String recipient = chatPerson.getText();
        sendMessage.setText("");
        String appendtxt = "@" + sender + ": " + getMess + "\n";
        
        sendMessage.setText("");
        SocketThread.sendMessage("msg to group", recipient, getMess);

    }//GEN-LAST:event_sendMessageToServer

    public static void appenfTextToGroupChat(String id, String sender, String message){
        String currentId = chatPerson.getText();
        
        if (currentId.equals(id)){
            if (sender.equals(Share.username)) {
                area.append("@You" + ": " + message + "\n");
            } else {
                area.append("@" + sender + ": " + message + "\n");
            }
        } else {
            for (int i = 0; i <= groups.size(); i++){
                if (id.equals(groups.get(i).getUsername())) {
                    switch (i) {
                        case 0: {
                            message1.setText(message);
                        }
                        
                        case 1: {
                            message2.setText(message);
                        }
                                 
                        case 2: {
                            message3.setText(message);
                        }

                        case 3: {
                            message4.setText(message);
                        }                        
                        
                        case 4: {
                            message5.setText(message);
                        }                        
                        
                        case 5: {
                            message6.setText(message);
                        }                        
                        
                    }
                }
            }
        }
    }
    
    public static void appendTextToBoxChat(String recipient, String message){
        String currentRecipient = chatPerson.getText();
        
        if (recipient.equals(currentRecipient)){
            area.append("@" + recipient + ": " + message);
        } else {
            for (int i = 0; i <= groups.size(); i++){
                if (recipient.equals(groups.get(i).getUsername())) {
                    switch (i) {
                        case 0: {
                            message1.setText(message);
                        }
                        
                        case 1: {
                            message2.setText(message);
                        }
                                 
                        case 2: {
                            message3.setText(message);
                        }

                        case 3: {
                            message4.setText(message);
                        }                        
                        
                        case 4: {
                            message5.setText(message);
                        }                        
                        
                        case 5: {
                            message6.setText(message);
                        }                        
                        
                    }
                }
            }
        }
        
        
    }
    
    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        // TODO add your handling code here:
        groupname4.setText("Edward Pham Hong Gia Bao");
        group1.setVisible(false);        
        group2.setVisible(false);
        group3.setVisible(false);
    }//GEN-LAST:event_searchMousePressed

    private void group5Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group5Click
        // TODO add your handling code here:
    }//GEN-LAST:event_group5Click

    private void group5Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group5Enter
        // TODO add your handling code here:
    }//GEN-LAST:event_group5Enter

    private void group5Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group5Exit
        // TODO add your handling code here:
    }//GEN-LAST:event_group5Exit

    private void group5Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group5Press
        // TODO add your handling code here:
        setColor1(group5);
        chatPerson.setText(groups.get(4).getUsername());
        setColor(group2);        
        setColor(group1);
        setColor(group3);
        setColor(group4);
        setColor(group6); 
                
        String username = groups.get(4).getUsername();
        ArrayList<MessageEntity> historyUser = MessageController.getHistoryMessage(groups.get(4).getUsername());
        area.setText("");
        for (MessageEntity i : historyUser){
            if (i.getsenderId().endsWith(File.readFromFile())) {
                String appendtxt = "@YOU: " + i.getMessage() + "\n";
                area.append(appendtxt);
            } else {
                String appendtxt = "@" + username + ": " + i.getMessage() + "\n";
                area.append(appendtxt);
            }
        }
    }//GEN-LAST:event_group5Press

    private void group6Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group6Click
        // TODO add your handling code here:
    }//GEN-LAST:event_group6Click

    private void group6Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group6Enter
        // TODO add your handling code here:
    }//GEN-LAST:event_group6Enter

    private void group6Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group6Exit
        // TODO add your handling code here:
    }//GEN-LAST:event_group6Exit

    private void group6Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_group6Press
        // TODO add your handling code here:
        setColor1(group6);
        chatPerson.setText(groups.get(5).getUsername());
        setColor(group2);        
        setColor(group1);
        setColor(group3);
        setColor(group5);
        setColor(group4); 
        
        String username = groups.get(5).getUsername();
        ArrayList<MessageEntity> historyUser = MessageController.getHistoryMessage(groups.get(5).getUsername());
        area.setText("");
        for (MessageEntity i : historyUser){
            if (i.getsenderId().endsWith(File.readFromFile())) {
                String appendtxt = "@You: " + i.getMessage() + "\n";
                area.append(appendtxt);
            } else {
                String appendtxt = "@" + username + ": " + i.getMessage() + "\n";
                area.append(appendtxt);
            }
        }
    }//GEN-LAST:event_group6Press

    private void moreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new groupMemberList(chatPerson.getText()).setVisible(true);
            }
        });
        
        
    }//GEN-LAST:event_moreMousePressed
    
    private static String colorString(String text) {
        StringBuilder coloredText = new StringBuilder("<html>");
        for (char c : text.toCharArray()) {
            coloredText.append("<font color='").append(getRandomColor()).append("'>").append(c).append("</font>");
        }
        coloredText.append("</html>");
        return coloredText.toString();
    }

    private static Color getRandomColor() {
        return new Color((int) (Math.random() * 256), (int) (Math.random() * 256), (int) (Math.random() * 256));
    }
    
    String getMessage(){
        String getMess = sendMessage.getText();
        return getMess;
    }

    void setColor(JPanel label) {
        label.setBackground(new Color(128, 161, 183));
        
    }
    
    void setColor1(JPanel label) {
        label.setBackground(new Color(128,206,202));
    }
    
    void resetColor(JPanel label) {
        label.setBackground(new Color(128, 190, 183));
    }
    
    
    final void initUser(){
        //ArrayList<Friend> friends = FriendController.apiFriendList();

        int lengFriend = groups.size();
        switch (lengFriend){
            case 0: {
                group1.setVisible(false);
                group2.setVisible(false);
                group3.setVisible(false);
                group4.setVisible(false);
                group5.setVisible(false);
                group6.setVisible(false);
                break;
            }
  
            case 1:{
                groupname1.setText(groups.get(0).getFullname());
                chatPerson.setText(groups.get(0).getUsername());
                group2.setVisible(false);
                group3.setVisible(false);
                group4.setVisible(false);
                group5.setVisible(false);
                group6.setVisible(false);
                break;
            }
                        
            case 2:{
                groupname1.setText(groups.get(0).getFullname());
                chatPerson.setText(groups.get(0).getUsername());
                groupname2.setText(groups.get(1).getFullname());
                group3.setVisible(false);
                group4.setVisible(false);
                group5.setVisible(false);
                group6.setVisible(false);
                break;
            }
                        
            case 3:{
                groupname1.setText(groups.get(0).getFullname());
                chatPerson.setText(groups.get(0).getUsername());
                groupname2.setText(groups.get(1).getFullname());                
                groupname3.setText(groups.get(2).getFullname());
                group4.setVisible(false);
                group5.setVisible(false);
                group6.setVisible(false);
                break;
            }
                        
            case 4:{
                groupname1.setText(groups.get(0).getFullname());
                chatPerson.setText(groups.get(0).getUsername());
                groupname2.setText(groups.get(1).getFullname());
                groupname3.setText(groups.get(2).getFullname());
                groupname4.setText(groups.get(3).getFullname());
                group5.setVisible(false);
                group6.setVisible(false);
                break;
            }
                        
            case 5:{
                groupname1.setText(groups.get(0).getFullname());
                chatPerson.setText(groups.get(0).getUsername());
                groupname2.setText(groups.get(1).getFullname());
                groupname3.setText(groups.get(2).getFullname());
                groupname4.setText(groups.get(3).getFullname());
                groupname5.setText(groups.get(4).getFullname());
                group6.setVisible(false);
                break;
            }
                        
            case 6:{
                groupname1.setText(groups.get(0).getFullname());
                chatPerson.setText(groups.get(0).getUsername());
                groupname2.setText(groups.get(1).getFullname());
                groupname3.setText(groups.get(2).getFullname());
                groupname4.setText(groups.get(3).getFullname());                
                groupname5.setText(groups.get(4).getFullname());
                groupname6.setText(groups.get(5).getFullname());

                break;
            }
            
        }
    }
    
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatboxGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatboxGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatboxGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatboxGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new chatboxGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea area;
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.JLabel avatar5;
    private javax.swing.JLabel avatar6;
    private javax.swing.JLabel chatLabel10;
    private javax.swing.JLabel chatLabel11;
    private javax.swing.JLabel chatLabel3;
    private javax.swing.JLabel chatLabel7;
    private javax.swing.JLabel chatLabel8;
    private javax.swing.JLabel chatLabel9;
    private static javax.swing.JLabel chatPerson;
    private javax.swing.JPanel chatbtn;
    private javax.swing.JPanel favouritebtn;
    private javax.swing.JPanel friendChat;
    private javax.swing.JPanel group1;
    private javax.swing.JPanel group2;
    private javax.swing.JPanel group3;
    private javax.swing.JPanel group4;
    private javax.swing.JPanel group5;
    private javax.swing.JPanel group6;
    private javax.swing.JPanel groupbtn;
    private javax.swing.JLabel groupname1;
    private javax.swing.JLabel groupname2;
    private javax.swing.JLabel groupname3;
    private javax.swing.JLabel groupname4;
    private javax.swing.JLabel groupname5;
    private javax.swing.JLabel groupname6;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homebtn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel logoutbtn;
    private static javax.swing.JLabel message1;
    private static javax.swing.JLabel message2;
    private static javax.swing.JLabel message3;
    private static javax.swing.JLabel message4;
    private static javax.swing.JLabel message5;
    private static javax.swing.JLabel message6;
    private javax.swing.JLabel more;
    private javax.swing.JPanel otherbtn;
    private javax.swing.JPanel send;
    private javax.swing.JTextField sendMessage;
    // End of variables declaration//GEN-END:variables
}
