/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main.view;

import java.awt.Color;
import javax.swing.*;
import Main.controller.friendController;
import Main.entity.Friend;
import java.util.ArrayList;

/**
 *
 * @author HP-PC
 */
public class chatbox extends javax.swing.JFrame {
    ArrayList<Friend> friends = new ArrayList<>();

    /**
     * Creates new form boxChat
     */
    public chatbox() {
        friends = friendController.apiFriendList();
        initComponents();
        initUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        home = new javax.swing.JPanel();
        friendChat = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        user1 = new javax.swing.JPanel();
        avatar1 = new javax.swing.JLabel();
        message1 = new javax.swing.JLabel();
        fullname1 = new javax.swing.JLabel();
        user2 = new javax.swing.JPanel();
        avatar2 = new javax.swing.JLabel();
        message2 = new javax.swing.JLabel();
        fullname2 = new javax.swing.JLabel();
        user3 = new javax.swing.JPanel();
        avatar3 = new javax.swing.JLabel();
        message3 = new javax.swing.JLabel();
        fullname3 = new javax.swing.JLabel();
        user4 = new javax.swing.JPanel();
        avatar4 = new javax.swing.JLabel();
        message4 = new javax.swing.JLabel();
        fullname4 = new javax.swing.JLabel();
        user5 = new javax.swing.JPanel();
        avatar5 = new javax.swing.JLabel();
        message5 = new javax.swing.JLabel();
        fullname5 = new javax.swing.JLabel();
        user6 = new javax.swing.JPanel();
        avatar6 = new javax.swing.JLabel();
        message6 = new javax.swing.JLabel();
        fullname6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        chatPerson = new javax.swing.JLabel();
        block = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spam = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        sendMessage = new javax.swing.JTextField();
        send = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        homebtn = new javax.swing.JPanel();
        chatLabel3 = new javax.swing.JLabel();
        chatbtn = new javax.swing.JPanel();
        chatLabel7 = new javax.swing.JLabel();
        groupbtn = new javax.swing.JPanel();
        chatLabel8 = new javax.swing.JLabel();
        favouritebtn = new javax.swing.JPanel();
        chatLabel9 = new javax.swing.JLabel();
        otherbtn = new javax.swing.JPanel();
        chatLabel10 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JPanel();
        chatLabel11 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Screen");

        home.setBackground(new java.awt.Color(255, 255, 255));

        friendChat.setBackground(new java.awt.Color(128, 161, 183));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("Search here");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/Main.icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );

        user1.setBackground(new java.awt.Color(128, 206, 202));
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1Click(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user1Press(evt);
            }
        });

        avatar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-user-30 (1).png"))); // NOI18N

        message1.setText("New message");

        fullname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullname1.setForeground(new java.awt.Color(255, 255, 255));
        fullname1.setText("Bao Pham Hong Gia");

        javax.swing.GroupLayout user1Layout = new javax.swing.GroupLayout(user1);
        user1.setLayout(user1Layout);
        user1Layout.setHorizontalGroup(
            user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user1Layout.setVerticalGroup(
            user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user1Layout.createSequentialGroup()
                        .addComponent(fullname1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        user2.setBackground(new java.awt.Color(128, 161, 183));
        user2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user2Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user2Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user2Press(evt);
            }
        });

        avatar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-user-30 (1).png"))); // NOI18N

        message2.setText("New message");

        fullname2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullname2.setForeground(new java.awt.Color(255, 255, 255));
        fullname2.setText("Phan Thanh An");

        javax.swing.GroupLayout user2Layout = new javax.swing.GroupLayout(user2);
        user2.setLayout(user2Layout);
        user2Layout.setHorizontalGroup(
            user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user2Layout.setVerticalGroup(
            user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user2Layout.createSequentialGroup()
                        .addComponent(fullname2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        user3.setBackground(new java.awt.Color(128, 161, 183));
        user3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user3Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user3Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user3Press(evt);
            }
        });

        avatar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-user-30 (1).png"))); // NOI18N

        message3.setText("New message");

        fullname3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullname3.setForeground(new java.awt.Color(255, 255, 255));
        fullname3.setText("Le Nguyen Thai");

        javax.swing.GroupLayout user3Layout = new javax.swing.GroupLayout(user3);
        user3.setLayout(user3Layout);
        user3Layout.setHorizontalGroup(
            user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user3Layout.setVerticalGroup(
            user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user3Layout.createSequentialGroup()
                        .addComponent(fullname3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        user4.setBackground(new java.awt.Color(128, 161, 183));
        user4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user4Click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user4Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user4Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user4Press(evt);
            }
        });

        avatar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-user-30 (1).png"))); // NOI18N

        message4.setText("New message");

        fullname4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullname4.setForeground(new java.awt.Color(255, 255, 255));
        fullname4.setText("Nguyen Nhat Nam");

        javax.swing.GroupLayout user4Layout = new javax.swing.GroupLayout(user4);
        user4.setLayout(user4Layout);
        user4Layout.setHorizontalGroup(
            user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user4Layout.setVerticalGroup(
            user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user4Layout.createSequentialGroup()
                        .addComponent(fullname4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        user5.setBackground(new java.awt.Color(128, 161, 183));
        user5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user5Click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user5Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user5Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user5Press(evt);
            }
        });

        avatar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-user-30 (1).png"))); // NOI18N

        message5.setText("New message");

        fullname5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullname5.setForeground(new java.awt.Color(255, 255, 255));
        fullname5.setText("Nguyen Nhat Nam");

        javax.swing.GroupLayout user5Layout = new javax.swing.GroupLayout(user5);
        user5.setLayout(user5Layout);
        user5Layout.setHorizontalGroup(
            user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user5Layout.setVerticalGroup(
            user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user5Layout.createSequentialGroup()
                        .addComponent(fullname5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        user6.setBackground(new java.awt.Color(128, 161, 183));
        user6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user6Click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user6Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user6Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user6Press(evt);
            }
        });

        avatar6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-user-30 (1).png"))); // NOI18N

        message6.setText("New message");

        fullname6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullname6.setForeground(new java.awt.Color(255, 255, 255));
        fullname6.setText("Nguyen Nhat Nam");

        javax.swing.GroupLayout user6Layout = new javax.swing.GroupLayout(user6);
        user6.setLayout(user6Layout);
        user6Layout.setHorizontalGroup(
            user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user6Layout.setVerticalGroup(
            user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user6Layout.createSequentialGroup()
                        .addComponent(fullname6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(message6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout friendChatLayout = new javax.swing.GroupLayout(friendChat);
        friendChat.setLayout(friendChatLayout);
        friendChatLayout.setHorizontalGroup(
            friendChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        friendChatLayout.setVerticalGroup(
            friendChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendChatLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(128, 161, 183));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-user-30 (1).png"))); // NOI18N

        chatPerson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatPerson.setForeground(new java.awt.Color(255, 255, 255));
        chatPerson.setText("Bao Pham Hong Gia");

        block.setBackground(new java.awt.Color(128, 161, 183));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-denied-30 (1).png"))); // NOI18N

        javax.swing.GroupLayout blockLayout = new javax.swing.GroupLayout(block);
        block.setLayout(blockLayout);
        blockLayout.setHorizontalGroup(
            blockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        blockLayout.setVerticalGroup(
            blockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        spam.setBackground(new java.awt.Color(128, 161, 183));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-spam-30.png"))); // NOI18N

        javax.swing.GroupLayout spamLayout = new javax.swing.GroupLayout(spam);
        spam.setLayout(spamLayout);
        spamLayout.setHorizontalGroup(
            spamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        spamLayout.setVerticalGroup(
            spamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(128, 190, 183));

        sendMessage.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageActionPerformed(evt);
            }
        });

        send.setBackground(new java.awt.Color(128, 190, 183));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-send-30 (1).png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendMouseExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sendMessageToServer(evt);
            }
        });

        javax.swing.GroupLayout sendLayout = new javax.swing.GroupLayout(send);
        send.setLayout(sendLayout);
        sendLayout.setHorizontalGroup(
            sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        sendLayout.setVerticalGroup(
            sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendMessage)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        area.setColumns(20);
        area.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(friendChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(friendChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(128, 190, 183));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-paper-plane-message-100.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ZALU");

        homebtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel3.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel3.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-home-30.png"))); // NOI18N
        chatLabel3.setText("Home");
        chatLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout homebtnLayout = new javax.swing.GroupLayout(homebtn);
        homebtn.setLayout(homebtnLayout);
        homebtnLayout.setHorizontalGroup(
            homebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homebtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homebtnLayout.setVerticalGroup(
            homebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        chatbtn.setBackground(new java.awt.Color(128, 161, 183));
        chatbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chatEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chatExit(evt);
            }
        });

        chatLabel7.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel7.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-chat-30.png"))); // NOI18N
        chatLabel7.setText("Chat Box");
        chatLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chatLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout chatbtnLayout = new javax.swing.GroupLayout(chatbtn);
        chatbtn.setLayout(chatbtnLayout);
        chatbtnLayout.setHorizontalGroup(
            chatbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chatbtnLayout.setVerticalGroup(
            chatbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        groupbtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel8.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel8.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N
        chatLabel8.setText("Group Chat");
        chatLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                groupExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                groupScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout groupbtnLayout = new javax.swing.GroupLayout(groupbtn);
        groupbtn.setLayout(groupbtnLayout);
        groupbtnLayout.setHorizontalGroup(
            groupbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        );
        groupbtnLayout.setVerticalGroup(
            groupbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        favouritebtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel9.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel9.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-star-30.png"))); // NOI18N
        chatLabel9.setText("Friend");
        chatLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favouriteEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favoutiteExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                favouriteScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout favouritebtnLayout = new javax.swing.GroupLayout(favouritebtn);
        favouritebtn.setLayout(favouritebtnLayout);
        favouritebtnLayout.setHorizontalGroup(
            favouritebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favouritebtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        favouritebtnLayout.setVerticalGroup(
            favouritebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        otherbtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel10.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel10.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-setting-30.png"))); // NOI18N
        chatLabel10.setText("Others");
        chatLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                otherEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                otherExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                otherScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout otherbtnLayout = new javax.swing.GroupLayout(otherbtn);
        otherbtn.setLayout(otherbtnLayout);
        otherbtnLayout.setHorizontalGroup(
            otherbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otherbtnLayout.setVerticalGroup(
            otherbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        logoutbtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel11.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel11.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-logout-30.png"))); // NOI18N
        chatLabel11.setText("Log out");
        chatLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout logoutbtnLayout = new javax.swing.GroupLayout(logoutbtn);
        logoutbtn.setLayout(logoutbtnLayout);
        logoutbtnLayout.setHorizontalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutbtnLayout.setVerticalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chatbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(groupbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(favouritebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(otherbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(groupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(favouritebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(otherbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeScreenMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new homeScreen().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_homeScreenMousePressed

    private void chatLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel7MouseClicked

    private void chatLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel7MousePressed

    private void chatLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel8MouseClicked

    private void groupScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupScreenMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override 
           public void run() {
               new groupchat().setVisible(true);
           }
        });
    }//GEN-LAST:event_groupScreenMousePressed

    private void chatLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel9MouseClicked

    private void favouriteScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouriteScreenMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override 
           public void run() {
               new friendScreen().setVisible(true);
           }
        });
    }//GEN-LAST:event_favouriteScreenMousePressed

    private void chatLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel10MouseClicked

    private void otherScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherScreenMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run(){
                new otherScreen().setVisible(true);
            }
        });
    }//GEN-LAST:event_otherScreenMousePressed

    private void chatLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel11MouseClicked

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run(){
                new loginForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_logoutMousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMessageActionPerformed

    private void sendMouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseEnter
        // TODO add your handling code here:
        //setColor(send);
    }//GEN-LAST:event_sendMouseEnter

    private void sendMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseExit
        resetColor(send);    }//GEN-LAST:event_sendMouseExit

    private void homeEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeEnter
        // TODO add your handling code here:
        //setColor(homebtn);
    }//GEN-LAST:event_homeEnter

    private void homeExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeExit
        // TODO add your handling code here:
        //resetColor(homebtn);
    }//GEN-LAST:event_homeExit

    private void groupExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupExit
        // TODO add your handling code here:
        //resetColor(groupbtn);
    }//GEN-LAST:event_groupExit

    private void favouriteEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouriteEnter
        // TODO add your handling code here:
        //setColor(favouritebtn);
    }//GEN-LAST:event_favouriteEnter

    private void favoutiteExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoutiteExit
        // TODO add your handling code here:
        //resetColor(favouritebtn);
    }//GEN-LAST:event_favoutiteExit

    private void otherEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherEnter
        // TODO add your handling code here:
        //setColor(otherbtn);

    }//GEN-LAST:event_otherEnter

    private void otherExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherExit
        // TODO add your handling code here:
        //resetColor(otherbtn);
    }//GEN-LAST:event_otherExit

    private void logoutEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutEnter
        // TODO add your handling code here:
        setColor(logoutbtn);
    }//GEN-LAST:event_logoutEnter

    private void logoutExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutExit
        // TODO add your handling code here:
        //resetColor(logoutbtn);
    }//GEN-LAST:event_logoutExit

    private void chatEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatEnter
        // TODO add your handling code here:
        //setColor(chatbtn);
    }//GEN-LAST:event_chatEnter

    private void chatExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatExit
        // TODO add your handling code here:
        //resetColor(chatbtn);
    }//GEN-LAST:event_chatExit

    private void user2Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2Enter
        // TODO add your handling code here:
        //setColor1(user2);
    }//GEN-LAST:event_user2Enter

    private void user2Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2Exit
        // TODO add your handling code here:
        //setColor(user2);
    }//GEN-LAST:event_user2Exit

    private void user3Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3Enter
        // TODO add your handling code here:
        //setColor1(user3);
    }//GEN-LAST:event_user3Enter

    private void user3Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3Exit
        // TODO add your handling code here:
        //setColor(user3);
    }//GEN-LAST:event_user3Exit

    private void user4Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4Enter
        // TODO add your handling code here:
       // setColor1(user4);
    }//GEN-LAST:event_user4Enter

    private void user4Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4Exit
        // TODO add your handling code here:
        //setColor(user4);
    }//GEN-LAST:event_user4Exit

    private void user4Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4Click
        // TODO add your handling code here:
        //setColor1(user4);
    }//GEN-LAST:event_user4Click

    private void user1Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1Click
        // TODO add your handling code here:
        //setColor1(user1);
    }//GEN-LAST:event_user1Click

    private void user2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseClicked
        // TODO add your handling code here:
        //setColor1(user2);
    }//GEN-LAST:event_user2MouseClicked

    private void user3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3MouseClicked
        // TODO add your handling code here:
       // setColor1(user3);
    }//GEN-LAST:event_user3MouseClicked

    private void user2Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2Press
        // TODO add your handling code here:
        chatPerson.setText(friends.get(1).getFullname());
        setColor1(user2);
        setColor(user1);        
        setColor(user3);
        setColor(user4);
        setColor(user5);
        setColor(user6);

    }//GEN-LAST:event_user2Press

    private void user1Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1Press
        // TODO add your handling code here:
        setColor1(user1);
        chatPerson.setText(friends.get(0).getFullname());
        setColor(user2);        
        setColor(user3);
        setColor(user4);        
        setColor(user5);
        setColor(user6);

    }//GEN-LAST:event_user1Press

    private void user3Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3Press
        // TODO add your handling code here:
        setColor1(user3);
        chatPerson.setText(friends.get(2).getFullname());
        setColor(user2);        
        setColor(user1);
        setColor(user4);
        setColor(user5);
        setColor(user6);
    }//GEN-LAST:event_user3Press

    private void user4Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4Press
        // TODO add your handling code here:
        setColor1(user4);
        chatPerson.setText(friends.get(3).getFullname());
        setColor(user2);        
        setColor(user1);
        setColor(user3);
        setColor(user5);
        setColor(user6);       
    }//GEN-LAST:event_user4Press

    private void sendMessageToServer(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageToServer
        // TODO add your handling code here:
        String mess = getMessage();
        String getMess = sendMessage.getText();
        String sender = "Bao Pham";
        sendMessage.setText("");
        String appendtxt = "@" + sender.toLowerCase() + ": " + getMess + "\n";
        area.append(appendtxt);
        sendMessage.setText("");
        System.out.println(mess);
    }//GEN-LAST:event_sendMessageToServer

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        // TODO add your handling code here:
        fullname4.setText("Edward Pham Hong Gia Bao");
        user1.setVisible(false);        
        user2.setVisible(false);
        user3.setVisible(false);
        
        


    }//GEN-LAST:event_searchMousePressed

    private void user5Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5Click
        // TODO add your handling code here:
    }//GEN-LAST:event_user5Click

    private void user5Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5Enter
        // TODO add your handling code here:
    }//GEN-LAST:event_user5Enter

    private void user5Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5Exit
        // TODO add your handling code here:
    }//GEN-LAST:event_user5Exit

    private void user5Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5Press
        // TODO add your handling code here:
        setColor1(user5);
        chatPerson.setText(friends.get(4).getFullname());
        setColor(user2);        
        setColor(user1);
        setColor(user3);
        setColor(user4);
        setColor(user6); 
    }//GEN-LAST:event_user5Press

    private void user6Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user6Click
        // TODO add your handling code here:
    }//GEN-LAST:event_user6Click

    private void user6Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user6Enter
        // TODO add your handling code here:
    }//GEN-LAST:event_user6Enter

    private void user6Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user6Exit
        // TODO add your handling code here:
    }//GEN-LAST:event_user6Exit

    private void user6Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user6Press
        // TODO add your handling code here:
        setColor1(user6);
        chatPerson.setText(friends.get(5).getFullname());
        setColor(user2);        
        setColor(user1);
        setColor(user3);
        setColor(user5);
        setColor(user4); 
    }//GEN-LAST:event_user6Press
    
    private static String colorString(String text) {
        StringBuilder coloredText = new StringBuilder("<html>");
        for (char c : text.toCharArray()) {
            coloredText.append("<font color='").append(getRandomColor()).append("'>").append(c).append("</font>");
        }
        coloredText.append("</html>");
        return coloredText.toString();
    }

    private static Color getRandomColor() {
        return new Color((int) (Math.random() * 256), (int) (Math.random() * 256), (int) (Math.random() * 256));
    }
    
    String getMessage(){
        String getMess = sendMessage.getText();
        return getMess;
    }

    void setColor(JPanel label) {
        label.setBackground(new Color(128, 161, 183));
        
    }
    
    void setColor1(JPanel label) {
        label.setBackground(new Color(128,206,202));
    }
    
    void resetColor(JPanel label) {
        label.setBackground(new Color(128, 190, 183));
    }
    
    
    final void initUser(){
        //ArrayList<Friend> friends = friendController.apiFriendList();

        int lengFriend = friends.size();
        switch (lengFriend){
            case 0: {
                user1.setVisible(false);
                user2.setVisible(false);
                user3.setVisible(false);
                user4.setVisible(false);
                user5.setVisible(false);
                user6.setVisible(false);
                break;
            }
  
            case 1:{
                fullname1.setText(friends.get(0).getFullname());
                chatPerson.setText(friends.get(0).getFullname());
                user2.setVisible(false);
                user3.setVisible(false);
                user4.setVisible(false);
                user5.setVisible(false);
                user6.setVisible(false);
                break;
            }
                        
            case 2:{
                fullname1.setText(friends.get(0).getFullname());
                chatPerson.setText(friends.get(0).getFullname());
                fullname2.setText(friends.get(1).getFullname());
                user3.setVisible(false);
                user4.setVisible(false);
                user5.setVisible(false);
                user6.setVisible(false);
                break;
            }
                        
            case 3:{
                fullname1.setText(friends.get(0).getFullname());
                chatPerson.setText(friends.get(0).getFullname());
                fullname2.setText(friends.get(1).getFullname());                
                fullname3.setText(friends.get(2).getFullname());
                user4.setVisible(false);
                user5.setVisible(false);
                user6.setVisible(false);
                break;
            }
                        
            case 4:{
                fullname1.setText(friends.get(0).getFullname());
                chatPerson.setText(friends.get(0).getFullname());
                fullname2.setText(friends.get(1).getFullname());
                fullname3.setText(friends.get(2).getFullname());
                fullname4.setText(friends.get(3).getFullname());
                user5.setVisible(false);
                user6.setVisible(false);
                break;
            }
                        
            case 5:{
                fullname1.setText(friends.get(0).getFullname());
                chatPerson.setText(friends.get(0).getFullname());
                fullname2.setText(friends.get(1).getFullname());
                fullname3.setText(friends.get(2).getFullname());
                fullname4.setText(friends.get(3).getFullname());
                fullname5.setText(friends.get(4).getFullname());
                user6.setVisible(false);
                break;
            }
                        
            case 6:{
                fullname1.setText(friends.get(0).getFullname());
                chatPerson.setText(friends.get(0).getFullname());
                fullname2.setText(friends.get(1).getFullname());
                fullname3.setText(friends.get(2).getFullname());
                fullname4.setText(friends.get(3).getFullname());                
                fullname5.setText(friends.get(4).getFullname());
                fullname6.setText(friends.get(5).getFullname());

                break;
            }
            
        }
    }
    
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new chatbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.JLabel avatar5;
    private javax.swing.JLabel avatar6;
    private javax.swing.JPanel block;
    private javax.swing.JLabel chatLabel10;
    private javax.swing.JLabel chatLabel11;
    private javax.swing.JLabel chatLabel3;
    private javax.swing.JLabel chatLabel7;
    private javax.swing.JLabel chatLabel8;
    private javax.swing.JLabel chatLabel9;
    private javax.swing.JLabel chatPerson;
    private javax.swing.JPanel chatbtn;
    private javax.swing.JPanel favouritebtn;
    private javax.swing.JPanel friendChat;
    private javax.swing.JLabel fullname1;
    private javax.swing.JLabel fullname2;
    private javax.swing.JLabel fullname3;
    private javax.swing.JLabel fullname4;
    private javax.swing.JLabel fullname5;
    private javax.swing.JLabel fullname6;
    private javax.swing.JPanel groupbtn;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homebtn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JLabel message1;
    private javax.swing.JLabel message2;
    private javax.swing.JLabel message3;
    private javax.swing.JLabel message4;
    private javax.swing.JLabel message5;
    private javax.swing.JLabel message6;
    private javax.swing.JPanel otherbtn;
    private javax.swing.JPanel send;
    private javax.swing.JTextField sendMessage;
    private javax.swing.JPanel spam;
    private javax.swing.JPanel user1;
    private javax.swing.JPanel user2;
    private javax.swing.JPanel user3;
    private javax.swing.JPanel user4;
    private javax.swing.JPanel user5;
    private javax.swing.JPanel user6;
    // End of variables declaration//GEN-END:variables
}
