/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main.view;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author HP-PC
 */
public class groupchat extends javax.swing.JFrame {

    /**
     * Creates new form boxChat
     */
    public groupchat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        home = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        user1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        user2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        user3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        user4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        menuFriend = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        emoji = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        attach = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        send = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        homebtn = new javax.swing.JPanel();
        chatLabel3 = new javax.swing.JLabel();
        chatbtn = new javax.swing.JPanel();
        chatLabel7 = new javax.swing.JLabel();
        groupbtn = new javax.swing.JPanel();
        chatLabel8 = new javax.swing.JLabel();
        favouritebtn = new javax.swing.JPanel();
        chatLabel9 = new javax.swing.JLabel();
        otherbtn = new javax.swing.JPanel();
        chatLabel10 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JPanel();
        chatLabel11 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Screen");

        home.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(128, 161, 183));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("Seach here");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/Main.icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );

        user1.setBackground(new java.awt.Color(128, 206, 202));
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1Click(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user1Press(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-female-user-30.png"))); // NOI18N

        jLabel7.setText("New message");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IOT");

        javax.swing.GroupLayout user1Layout = new javax.swing.GroupLayout(user1);
        user1.setLayout(user1Layout);
        user1Layout.setHorizontalGroup(
            user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user1Layout.setVerticalGroup(
            user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        user2.setBackground(new java.awt.Color(128, 161, 183));
        user2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user2Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user2Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user2Press(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-female-user-30.png"))); // NOI18N

        jLabel16.setText("New message");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Java Group");

        javax.swing.GroupLayout user2Layout = new javax.swing.GroupLayout(user2);
        user2.setLayout(user2Layout);
        user2Layout.setHorizontalGroup(
            user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user2Layout.setVerticalGroup(
            user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        user3.setBackground(new java.awt.Color(128, 161, 183));
        user3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user3Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user3Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user3Press(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-female-user-30.png"))); // NOI18N

        jLabel19.setText("New message");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Ae chung ta");

        javax.swing.GroupLayout user3Layout = new javax.swing.GroupLayout(user3);
        user3.setLayout(user3Layout);
        user3Layout.setHorizontalGroup(
            user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user3Layout.setVerticalGroup(
            user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user3Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        user4.setBackground(new java.awt.Color(128, 161, 183));
        user4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user4Click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user4Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user4Exit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user4Press(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-female-user-30.png"))); // NOI18N

        jLabel22.setText("New message");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Hoi nhung ng iu Hoa");

        javax.swing.GroupLayout user4Layout = new javax.swing.GroupLayout(user4);
        user4.setLayout(user4Layout);
        user4Layout.setHorizontalGroup(
            user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        user4Layout.setVerticalGroup(
            user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user4Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(128, 161, 183));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-female-user-30.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bao Pham Hong Gia");

        menuFriend.setBackground(new java.awt.Color(128, 161, 183));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-menu-30 (1).png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFriendMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuFriendExit(evt);
            }
        });

        javax.swing.GroupLayout menuFriendLayout = new javax.swing.GroupLayout(menuFriend);
        menuFriend.setLayout(menuFriendLayout);
        menuFriendLayout.setHorizontalGroup(
            menuFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFriendLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        menuFriendLayout.setVerticalGroup(
            menuFriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(menuFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(menuFriend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(128, 190, 183));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        emoji.setBackground(new java.awt.Color(128, 190, 183));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-smile-30 (1).png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emojiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emojiMouseExit(evt);
            }
        });

        javax.swing.GroupLayout emojiLayout = new javax.swing.GroupLayout(emoji);
        emoji.setLayout(emojiLayout);
        emojiLayout.setHorizontalGroup(
            emojiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emojiLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        emojiLayout.setVerticalGroup(
            emojiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        attach.setBackground(new java.awt.Color(128, 190, 183));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-add-link-30.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attachMouseExit(evt);
            }
        });

        javax.swing.GroupLayout attachLayout = new javax.swing.GroupLayout(attach);
        attach.setLayout(attachLayout);
        attachLayout.setHorizontalGroup(
            attachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attachLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        attachLayout.setVerticalGroup(
            attachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attachLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        send.setBackground(new java.awt.Color(128, 190, 183));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-send-30 (1).png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendMouseExit(evt);
            }
        });

        javax.swing.GroupLayout sendLayout = new javax.swing.GroupLayout(send);
        send.setLayout(sendLayout);
        sendLayout.setHorizontalGroup(
            sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        sendLayout.setVerticalGroup(
            sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emoji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(attach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emoji, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(128, 190, 183));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-paper-plane-message-100.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ZALU");

        homebtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel3.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel3.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-home-30.png"))); // NOI18N
        chatLabel3.setText("Home");
        chatLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout homebtnLayout = new javax.swing.GroupLayout(homebtn);
        homebtn.setLayout(homebtnLayout);
        homebtnLayout.setHorizontalGroup(
            homebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homebtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homebtnLayout.setVerticalGroup(
            homebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        chatbtn.setBackground(new java.awt.Color(128, 190, 183));
        chatbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chatEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chatExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chatMoousePressed(evt);
            }
        });

        chatLabel7.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel7.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-chat-30.png"))); // NOI18N
        chatLabel7.setText("Chat Box");
        chatLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chatboxMousePressed(evt);
            }
        });

        javax.swing.GroupLayout chatbtnLayout = new javax.swing.GroupLayout(chatbtn);
        chatbtn.setLayout(chatbtnLayout);
        chatbtnLayout.setHorizontalGroup(
            chatbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chatbtnLayout.setVerticalGroup(
            chatbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        groupbtn.setBackground(new java.awt.Color(128, 161, 183));

        chatLabel8.setBackground(new java.awt.Color(128, 161, 183));
        chatLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel8.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-group-30.png"))); // NOI18N
        chatLabel8.setText("Group Chat");
        chatLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                groupExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chatLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout groupbtnLayout = new javax.swing.GroupLayout(groupbtn);
        groupbtn.setLayout(groupbtnLayout);
        groupbtnLayout.setHorizontalGroup(
            groupbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );
        groupbtnLayout.setVerticalGroup(
            groupbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        favouritebtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel9.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel9.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-star-30.png"))); // NOI18N
        chatLabel9.setText("Favourite");
        chatLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favouriteEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favoutiteExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                favouriteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout favouritebtnLayout = new javax.swing.GroupLayout(favouritebtn);
        favouritebtn.setLayout(favouritebtnLayout);
        favouritebtnLayout.setHorizontalGroup(
            favouritebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favouritebtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        favouritebtnLayout.setVerticalGroup(
            favouritebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        otherbtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel10.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel10.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-setting-30.png"))); // NOI18N
        chatLabel10.setText("Others");
        chatLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                otherEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                otherExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                otherScreenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout otherbtnLayout = new javax.swing.GroupLayout(otherbtn);
        otherbtn.setLayout(otherbtnLayout);
        otherbtnLayout.setHorizontalGroup(
            otherbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otherbtnLayout.setVerticalGroup(
            otherbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        logoutbtn.setBackground(new java.awt.Color(128, 190, 183));

        chatLabel11.setBackground(new java.awt.Color(128, 190, 183));
        chatLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatLabel11.setForeground(new java.awt.Color(255, 255, 255));
        chatLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/icon/icons8-logout-30.png"))); // NOI18N
        chatLabel11.setText("Log out");
        chatLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutExit(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout logoutbtnLayout = new javax.swing.GroupLayout(logoutbtn);
        logoutbtn.setLayout(logoutbtnLayout);
        logoutbtnLayout.setHorizontalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutbtnLayout.setVerticalGroup(
            logoutbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chatbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(groupbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(favouritebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(otherbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(groupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(favouritebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(otherbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new homeScreen().setVisible(true);
            }
        });
    }//GEN-LAST:event_homeMousePressed

    private void chatLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel7MouseClicked

    private void chatboxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatboxMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new chatbox().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_chatboxMousePressed

    private void chatLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel8MouseClicked

    private void chatLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel8MousePressed

    private void chatLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel9MouseClicked

    private void favouriteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouriteMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new favourite().setVisible(true);
            }
        });
    }//GEN-LAST:event_favouriteMousePressed

    private void chatLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel10MouseClicked

    private void otherScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherScreenMousePressed
        // TODO add your handling code here:
                dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new otherScreen().setVisible(true);
            }
        });
    }//GEN-LAST:event_otherScreenMousePressed

    private void chatLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chatLabel11MouseClicked

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_logoutMousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void emojiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiMouseEntered
        // TODO add your handling code here:
        setColor(emoji);
    }//GEN-LAST:event_emojiMouseEntered

    private void emojiMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiMouseExit
        // TODO add your handling code here:        
        resetColor(emoji);
    }//GEN-LAST:event_emojiMouseExit

    private void attachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attachMouseEntered
        // TODO add your handling code here:
        setColor(attach);

    }//GEN-LAST:event_attachMouseEntered

    private void attachMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attachMouseExit
        // TODO add your handling code here:
        resetColor(attach);
    }//GEN-LAST:event_attachMouseExit

    private void sendMouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseEnter
        // TODO add your handling code here:
        setColor(send);
    }//GEN-LAST:event_sendMouseEnter

    private void sendMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseExit
        resetColor(send);    }//GEN-LAST:event_sendMouseExit

    private void menuFriendMouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFriendMouseEnter
        // TODO add your handling code here:
        //resetColor(menuFriend);
    }//GEN-LAST:event_menuFriendMouseEnter

    private void MenuFriendExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFriendExit
        // TODO add your handling code here:
        //setColor(menuFriend);
    }//GEN-LAST:event_MenuFriendExit

    private void homeEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeEnter
        // TODO add your handling code here:
        setColor(homebtn);
    }//GEN-LAST:event_homeEnter

    private void homeExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeExit
        // TODO add your handling code here:
       // resetColor(homebtn);
    }//GEN-LAST:event_homeExit

    private void groupExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupExit
        // TODO add your handling code here:
       // resetColor(groupbtn);
    }//GEN-LAST:event_groupExit

    private void favouriteEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouriteEnter
        // TODO add your handling code here:
       // setColor(favouritebtn);
    }//GEN-LAST:event_favouriteEnter

    private void favoutiteExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoutiteExit
        // TODO add your handling code here:
        //resetColor(favouritebtn);
    }//GEN-LAST:event_favoutiteExit

    private void otherEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherEnter
        // TODO add your handling code here:
       // setColor(otherbtn);

    }//GEN-LAST:event_otherEnter

    private void otherExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherExit
      //  // TODO add your handling code here:
       // resetColor(otherbtn);
    }//GEN-LAST:event_otherExit

    private void logoutEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutEnter
        // TODO add your handling code here:
      //  setColor(logoutbtn);
    }//GEN-LAST:event_logoutEnter

    private void logoutExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutExit
        // TODO add your handling code here:
        //resetColor(logoutbtn);
    }//GEN-LAST:event_logoutExit

    private void chatEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatEnter
        // TODO add your handling code here:
       // setColor(chatbtn);
    }//GEN-LAST:event_chatEnter

    private void chatExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatExit
        // TODO add your handling code here:
       // resetColor(chatbtn);
    }//GEN-LAST:event_chatExit

    private void user2Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2Enter
        // TODO add your handling code here:
        //setColor1(user2);
    }//GEN-LAST:event_user2Enter

    private void user2Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2Exit
        // TODO add your handling code here:
        //setColor(user2);
    }//GEN-LAST:event_user2Exit

    private void user3Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3Enter
        // TODO add your handling code here:
        //setColor1(user3);
    }//GEN-LAST:event_user3Enter

    private void user3Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3Exit
        // TODO add your handling code here:
        //setColor(user3);
    }//GEN-LAST:event_user3Exit

    private void user4Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4Enter
        // TODO add your handling code here:
       // setColor1(user4);
    }//GEN-LAST:event_user4Enter

    private void user4Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4Exit
        // TODO add your handling code here:
        //setColor(user4);
    }//GEN-LAST:event_user4Exit

    private void user4Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4Click
        // TODO add your handling code here:
        //setColor1(user4);
    }//GEN-LAST:event_user4Click

    private void user1Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1Click
        // TODO add your handling code here:
        //setColor1(user1);
    }//GEN-LAST:event_user1Click

    private void user2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseClicked
        // TODO add your handling code here:
        //setColor1(user2);
    }//GEN-LAST:event_user2MouseClicked

    private void user3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3MouseClicked
        // TODO add your handling code here:
       // setColor1(user3);
    }//GEN-LAST:event_user3MouseClicked

    private void user2Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2Press
        // TODO add your handling code here:
        setColor1(user2);
        setColor(user1);        
        setColor(user3);
        setColor(user4);

    }//GEN-LAST:event_user2Press

    private void user1Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1Press
        // TODO add your handling code here:
        setColor1(user1);
        setColor(user2);        
        setColor(user3);
        setColor(user4);
    }//GEN-LAST:event_user1Press

    private void user3Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3Press
        // TODO add your handling code here:
        setColor1(user3);
        setColor(user2);        
        setColor(user1);
        setColor(user4);
    }//GEN-LAST:event_user3Press

    private void user4Press(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4Press
        // TODO add your handling code here:
        setColor1(user4);
        setColor(user2);        
        setColor(user1);
        setColor(user3);
    }//GEN-LAST:event_user4Press

    private void chatMoousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatMoousePressed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new chatbox().setVisible(true);
            }
        });
    }//GEN-LAST:event_chatMoousePressed


    void setColor(JPanel label) {
        label.setBackground(new Color(128, 161, 183));
        
    }
    
    void setColor1(JPanel label) {
        label.setBackground(new Color(128,206,202));
    }
    
    void resetColor(JPanel label) {
        label.setBackground(new Color(128, 190, 183));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(groupchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(groupchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(groupchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(groupchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new groupchat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attach;
    private javax.swing.JLabel chatLabel10;
    private javax.swing.JLabel chatLabel11;
    private javax.swing.JLabel chatLabel3;
    private javax.swing.JLabel chatLabel7;
    private javax.swing.JLabel chatLabel8;
    private javax.swing.JLabel chatLabel9;
    private javax.swing.JPanel chatbtn;
    private javax.swing.JPanel emoji;
    private javax.swing.JPanel favouritebtn;
    private javax.swing.JPanel groupbtn;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homebtn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JPanel menuFriend;
    private javax.swing.JPanel otherbtn;
    private javax.swing.JPanel send;
    private javax.swing.JPanel user1;
    private javax.swing.JPanel user2;
    private javax.swing.JPanel user3;
    private javax.swing.JPanel user4;
    // End of variables declaration//GEN-END:variables
}
